# Generated by Django 3.1.3 on 2020-11-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('skill', models.CharField(max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
